language: python

cache:
  directories:
  - $HOME/nats-server

python:
  - "3.8"
  - "3.9"
  - "3.10"

before_install:
  - bash ./script/install_nats.sh

before_script:
  - export PATH=$HOME/nats-server:$PATH

install:
  - pip install -e .[nkeys]

script:
  - make ci
  
notifications:
  email: false

sudo: true
dist: xenial

jobs:
  include:
  - name: "Python: 3.8/uvloop"
    python: "3.8"
    install:
      - pip install uvloop
  allow_failures:
    python:
      - "3.8"
